ci: Creazte separate jobs for each platforms

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,31 +41,73 @@ jobs:
         if: env.FAIL_TASK == 'true'
         run: exit 1
 
-  build:
-    name: Build on windows-latest, ubuntu-latest and macos-latests runners
-    strategy:
-      fail-fast: true
-      matrix: # Make one workflow run on the multiple platforms
-        platform: [windows-latest, ubuntu-latest, macos-latest]
-    runs-on: ${{ matrix.platform }}
-
+  build_linux:
+    name: Build the project on epitest docker
+    runs-on: ubuntu-latest
+    needs: [clean_repo]
+    container: epitechcontent/epitest-docker:latest
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Get Cmake latest
-        uses: lukka/get-cmake@latest
-
-      - name: Restore artifacts, or setup  vcpkg (do not install any package)
-        uses: lukka/run-vcpkg@v10
+      - name: Checkout repo
+        uses: actions/checkout@v3
         with:
-          vcpkgGitCommitId: '57d3194e702a2959e86a6748999ad71fc24f7922'
+          fetch-depth: 0
 
-      - name: Run Cmake with CMakePreset.json and vcpkg.json
-        uses: lukka/run-cmake@v10
+      - name: Configure CMake
+        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
+        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
+        run: cmake -B ${{github.workspace}}/build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE='${{ github.workspace }}/cmake/vcpkg.cmake'
+
+      - name: Build
+        # Build your program with the given configuration
+        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+
+#      - name: Check executables
+#        run: |
+#          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
+#          SERV_BINARIES="${{ env.SERV_BIN }}"
+#          IFS=$','
+#          for BIN in $SERV_BINARIES; do
+#            if [ ! -f "${BIN}" ]; then
+#              echo "::error file=${BIN},title=Binary not found::${BIN}"
+#              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+#            fi
+#            if [ ! -x "${BIN}" ]; then
+#              echo "::error file=${BIN},title=Binary is not executable::${BIN}"
+#              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+#            fi
+#          done
+#          CLI_BINARIES="${{ env.CLIENT_BIN }}"
+#          IFS=$','
+#          for BIN in $CLI_BINARIES; do
+#            if [ ! -f "${BIN}" ]; then
+#              echo "::error file=${BIN},title=Binary not found::${BIN}"
+#              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+#            fi
+#            if [ ! -x "${BIN}" ]; then
+#              echo "::error file=${BIN},title=Binary is not executable::${BIN}"
+#              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
+#            fi
+#          done
+#
+#      - name: Check if task failed
+#        if: env.FAIL_TASK == 'true'
+#        run: exit 1
+
+  build_windows:
+    name: Build the project on windows-latest
+    runs-on: windows-latest
+    needs: [clean_repo]
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
         with:
-          configurePreset: 'ninja-multi-vcpkg'
-          buildPreset: 'ninja-multi-vcpkg'
+          fetch-depth: 0
 
+      - name: Configure CMake
+        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST_SUITE=TRUE -DCMAKE_TOOLCHAIN_FILE='${{ github.workspace }}/cmake/vcpkg.cmake'
+
+      - name: Build
+        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j
 
   to_github:
     name: Push content of the current repo on mirror
